#! /usr/bin/bash
termux-setup-storage
sleep 10
apt update && apt upgrade -y
yes | pkg install root-repo x11-repo -y
yes | pkg install python clang libxml2 libxslt pkg-config libllvm binutils ldd -y
yes | pkg install wget curl git python-lxml -y
yes | pip install requests requests[socks] beautifulsoup4 
wget https://raw.githubusercontent.com/BotNet90/myACT/main/users
chmod +x users
mkdir /storage/emulated/0/dataku
touch /storage/emulated/0/dataku/regist.txt
touch /storage/emulated/0/dataku/hasil.txt 
chmod +x /storage/emulated/0/dataku/regist.txt
chmod +x /storage/emulated/0/dataku/hasil.txt 
value="true"; key="allow-external-apps"; file="/data/data/com.termux/files/home/.termux/termux.properties"; mkdir -p "$(dirname "$file")"; chmod 700 "$(dirname "$file")"; if ! grep -E '^'"$key"'=.*' $file &>/dev/null; then [[ -s "$file" && ! -z "$(tail -c 1 "$file")" ]] && newline=$'\n' || newline=""; echo "$newline$key=$value" >> "$file"; else sed -i'' -E 's/^'"$key"'=.*/'"$key=$value"'/' $file; fi
rm -rf start
